### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by Frag1337** [KirillMysnik/sp-map-cycle#3]
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 162, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 193, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 76, in _load
    self.module.load()
  File "..\addons\source-python\plugins\map_cycle\map_cycle.py", line 774, in load
    reload_maps_from_mapcycle()
  File "..\addons\source-python\plugins\map_cycle\map_cycle.py", line 252, in reload_maps_from_mapcycle
    reload_map_list()
  File "..\addons\source-python\plugins\map_cycle\map_cycle.py", line 222, in reload_map_list
    text=server_map.name,
  File "..\addons\source-python\plugins\map_cycle\core\server_maps.py", line 106, in name
    if config_manager['predict_missing_filename']:
  File "..\addons\source-python\packages\custom\controlled_cvars\__init__.py", line 51, in __getitem__
    return self._saved_values[name]

KeyError: 'predict_missing_filename'
```

**Comment by KirillMysnik** [comment]
Thank you. 5a6b2381b20908b693fefdd88ae8e50ec78a8622 should fix the issue.
