### ISSUE TITLE
Loading Error #2

### ISSUE THREAD

**Issue by Frag1337** [KirillMysnik/sp-map-cycle#4]
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 162, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 193, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 76, in _load
    self.module.load()
  File "..\addons\source-python\plugins\map_cycle\map_cycle.py", line 829, in load
    broadcast(common_strings['loaded'])
  File "..\addons\source-python\plugins\map_cycle\core\mcplayers.py", line 38, in broadcast
    tell([mcplayer.player for mcplayer in mcplayers.values()], message)
  File "..\addons\source-python\plugins\map_cycle\core\mcplayers.py", line 29, in tell
    message = message.tokenized(**message.tokens, **COLOR_SCHEME)

AttributeError: 'TranslationStrings' object has no attribute 'tokenized'
```

**Comment by KirillMysnik** [comment]
To be able to load the plugin, apply these upcoming changes to your SP installation
https://github.com/KirillMysnik/Source.Python/blob/8aebe31c3aca1aab47d04145ae323935876f65b7/addons/source-python/packages/source-python/translations/strings.py
